# Generated by Django 4.2.15 on 2024-08-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Cuisine',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=255)),
        ('famous_dish', models.CharField(max_length=255)),
      ],
    ),
    migrations.CreateModel(
      name='Recipe',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=255)),
        ('ingredients', models.CharField(max_length=255)),
      ],
    ),
  ]
