# Generated by Django 4.2.15 on 2024-08-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kangacook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kangacook.cuisine'),
            preserve_default=False,
        ),
    ]
